version: '3.8'

services:
  java-bank-api:
    container_name: java-bank
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3